open Core

module Logon = struct
  type t =
    { session_id: string;
      time: Time_ns.t;
      user: string;
      credentials: string;
    }
  [@@deriving fields]
end

(* Logon.user is generated by [@@deriving fields] annotation *)
let get_users logons =
  List.dedup_and_sort ~compare:String.compare
(List.map logons ~f:Logon.user)